services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    expose:
     - 8080/tcp
    ports:
     - 8080:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ollama:11434
     - AUTOMATIC1111_BASE_URL=http://host.docker.internal:7860
     # uncomment the following if you are running ollama on the docker host and remove the ollama service below
     #- OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
     - ollama

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    expose:
     - 11434/tcp
    ports:
     - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]

  open-webui-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_URL=http://open-webui:8080
    command: tunnel --no-autoupdate run --token ${open_webui_tunnel_token}
    # demo mode
    # command: tunnel --no-autoupdate
    network_mode: host
    depends_on:
      - open-webui

  ollama-tunnel:
   image: cloudflare/cloudflared:latest
   restart: unless-stopped
   environment:
     - TUNNEL_URL=http://ollama:11434
   command: tunnel --no-autoupdate run --token ${ollama_tunnel_token}
   # demo mode
   # command: tunnel --no-autoupdate
   network_mode: host
   depends_on:
     - ollama

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  ollama:
  open-webui:
